services:
  - type: web
    name: perplexity-clone
    env: node
    buildCommand: |
      npm install
      npm run build
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT &
      npm start
    envVars:
      - key: PORT
        value: 10000
      - key: API_URL
        value: "http://localhost:10000"
      - key: NODE_ENV
        value: production
